spring.application.name=ApiGym

spring.datasource.url=jdbc:postgresql://localhost:5432/ApiGym
spring.datasource.username=postgres
spring.datasource.password=caio040406
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

