spring:
  application:
    name : spring-boot-essentials-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/ApiGym
    username: postgres
    password: caio040406

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    expiration: ${JWT_EXPIRATION:900000} #15 minutos
    key: ${JWT_KEY:DQ2fLIctIjGMKLxp21XDw=0&#!b&!Drox_!MA-ep6zx#S3wBe!akGT7svv2K5_bpZ$oER2E50v3bEgkyUPdgPFt=zNELe-ZqpDKVhVSKx2T7S6lslkZCPWce=BeYe7GiNKyo&3RHI_nzXt79$A!kOt!u=xVVvejDMBwvYVl#Ph&Cw_g47eNuFq65pbQgpo0SOLa3CxV#H7qS4Km!3TqL!o6f2K1=qzm0cbIsqqO9Ac8C9TrpADswS2U0-o6ahdZrauXv4pEKg#q5vl-ynkdcxbWXZeLQdqh9U$DJGQyEUZx7x55ZFwk#YEuGe99NR7aPvqAzpiFZ56syDnbeG#UCu5tS}





